---
title: "Problem Set 1"
author: 
  - Junjie LIU:
      email: liuj13@tcd.ie
      institute: [TCD-polisci]
      correspondence: true
date: "2023-09-28"
institute:
  - TCD-polisci: Department of Political Science, Trinity College Dublin, 2 Clare, Street, Dublin 2, Ireland
toc: false
output:
  bookdown::pdf_document2:
    includes:
      in_header: dependency.sty
    pandoc_args:
      - --lua-filter=/workspaces/Extras/scholarly-metadata.lua
      - --lua-filter=/workspaces/Extras/author-info-blocks.lua
---

\section*{Instructions}
	\begin{itemize}
	\item Please show your work! You may lose points by simply writing in the answer. If the problem requires you to execute commands in \texttt{R}, please include the code you used to get your answers. Please also include the \texttt{.R} file that contains your code. If you are not sure if work needs to be shown for a particular problem, please ask.
  \item Your homework should be submitted electronically on GitHub.
  \item This problem set is due before 23:59 on Sunday October 1, 2023. No late assignments will be accepted.
  \item Total available points for this homework is 80.
\end{itemize}

\section*{Question 1 (40 points): Education}

A school counselor was curious about the average of IQ of the students in her school and took a random sample of 25 students' IQ scores. The following is the data set:

\lstinputlisting[language=R, firstline=36, lastline=36]{PS01.R}  
\vspace{1cm}
\begin{enumerate}
	\item Find a 90\% confidence interval for the average student IQ in the school.\\
	\item Next, the school counselor was curious  whether  the average student IQ in her school is higher than the average IQ score (100) among all the schools in the country.\\ 
  \noindent Using the same sample, conduct the appropriate hypothesis test with $\alpha=0.05$.
\end{enumerate}

\subsection*{\textcolor{blue}{Answer of Question 1}}

\textcolor{blue}{For the first sub-task in Question 1:}
```{R, tidy=TRUE, tidy.opts=list(width.cutoff=60)}
y <- c(105, 69, 86, 100, 82, 111, 104, 110, 87, 108, 87, 90, 94, 113, 112, 98, 80, 97, 95, 111, 114, 89, 95, 126, 98)

### For the Q1.1
q11.n <- length(y)
q11.y_bar <- mean(y)
q11.y_std <- sqrt(var(y))

q11.margin_left <- q11.y_bar - qt(0.05, q11.n, lower.tail=F) * q11.y_std / sqrt(q11.n)
q11.margin_right <- q11.y_bar + qt(0.05, q11.n, lower.tail=F) * q11.y_std / sqrt(q11.n)
sprintf("The 90%% CI of the Avg IQ is (%1$.3f, %2$.3f)", q11.margin_left, q11.margin_right)

```

\noindent \textcolor{blue}{For the second sub-task of Question 1:
\begin{enumerate}
  \item[$\mathcal{H}_0$]: The average student IQ in her school is not higher than the average IQ score (100) among all the scools in the country, i.e. $\text{IQ}_{\text{school}} \leq \text{IQ})_{\text{country}}$
  \item[$\mathcal{H}_1$]: The average student IQ in her school is higher than the average IQ score (100) among all the schools in the country, i.e. $\text{IQ}_{\text{school}} > \text{IQ})_{\text{country}}$
\end{enumerate}
}
```{R, tidy=TRUE, tidy.opts=list(width.cutoff=60)}
### For the Q1.2
alpha <- 0.05
q12.t_test <- t.test(y, mu=100, conf.level=(1 - alpha), alternative="greater")
print(q12.t_test)
```
\textcolor{blue}{Since the p-value is $0.7215$, we could not reject the null hypothesis.}

\newpage
\section*{Question 2 (40 points): Political Economy}

\noindent Researchers are curious about what affects the amount of money communities spend on addressing homelessness. The following variables constitute our data set about social welfare expenditures in the USA.

\begin{tabular}{r|l}
	\texttt{State} &\emph{50 states in US} \\
	\texttt{Y} & \emph{per capita expenditure on shelters/housing assistance in state}\\
	\texttt{X1} &\emph{per capita personal income in state} \\
	\texttt{X2} &  \emph{Number of residents per 100,000 that are "financially insecure" in state}\\
	\texttt{X3} &  \emph{Number of people per thousand residing in urban areas in state} \\
	\texttt{Region} &  \emph{1=Northeast, 2= North Central, 3= South, 4=West} \\
\end{tabular}

\vspace{.5cm}
\noindent Explore the \texttt{expenditure} data set and import data into \texttt{R}.
\vspace{.5cm}
\lstinputlisting[language=R, firstline=54, lastline=54]{PS01.R}  
\vspace{.5cm}
\begin{itemize}

\item
Please plot the relationships among \emph{Y}, \emph{X1}, \emph{X2}, and \emph{X3}? What are the correlations among them (you just need to describe the graph and the relationships among them)?
\vspace{.5cm}
\item
Please plot the relationship between \emph{Y} and \emph{Region}? On average, which region has the highest per capita expenditure on housing assistance?
\vspace{.5cm}
\item
Please plot the relationship between \emph{Y} and \emph{X1}? Describe this graph and the relationship. Reproduce the above graph including one more variable \emph{Region} and display different regions with different types of symbols and colors.
\end{itemize}

\subsection*{\textcolor{blue}{Answer of Question 2}}

\textcolor{blue}{For the first sub-task in Question 2}:
```{R, tidy=TRUE, tidy.opts=list(width.cutoff=50)}
expenditure <- read.table("https://raw.githubusercontent.com/ASDS-TCD/StatsI_Fall2023/main/datasets/expenditure.txt", header=T)
summary(expenditure)
### For the Q2.1
pairs(expenditure[,2:5], main = "Relationship Between Y, X1, X2, and X3")
correlation <- cor(expenditure[, c("Y", "X1", "X2", "X3")])
print(correlation)
```
\textcolor{blue}{For the second sub-task in Question 2}:

```{R, tidy=TRUE, tidy.opts=list(width.cutoff=50)}
par(mfrow=c(1, 2))
plot(expenditure$Region, expenditure$Y, xlab="Region", ylab="Expenditure (Y)", main = "Y vs Region")
boxplot(expenditure$Y~expenditure$Region, xlab="Region", ylab="Expenditure (Y)", main="Y vs Region (BoxPlot)")
```
\textcolor{blue}{The figure on the left is the scattor plot and the figure on the right is the box plot of \emph{Y} and \emph{Region}, where both of them with the same x-axis and y-axis, i.e, the x-axis represents the Region and the y-axis represents the Y (expenditure) values.}

\noindent \textcolor{blue}{For the third sub-task of Question 2:}
```{R, tidy=TRUE, tidy.opts=list(width.cutoff=50)}
library(ggplot2)
# Create the scatter plot with Y and X1
ggplot(expenditure, aes(x = X1, y = Y)) +
  geom_point(aes(shape = factor(Region), color = factor(Region))) +
  labs(x = "X1", y = "Y", title = "Relationship between Y and X1") +
  scale_shape_manual(values = c(1, 2, 3, 4)) +
  scale_color_manual(values = c("red", "blue", "green", "purple")) +
  theme_minimal()
```
