---
title: "Problem Set 4 - My Answer"
author: 
  - Junjie LIU:
      email: liuj13@tcd.ie
      institute: [TCD-polisci]
      correspondence: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
institute:
  - TCD-polisci: Department of Political Science, Trinity College Dublin, 2 Clare, Street, Dublin 2, Ireland
toc: false
output:
  bookdown::pdf_document2:
    includes:
      in_header: dependency.sty
    pandoc_args:
      - --lua-filter=../../../environment/scholarly-metadata.lua
      - --lua-filter=../../../environment/author-info-blocks.lua
---

\section*{Instructions}
	\begin{itemize}
	\item Please show your work! You may lose points by simply writing in the answer. If the problem requires you to execute commands in \texttt{R}, please include the code you used to get your answers. Please also include the \texttt{.R} file that contains your code. If you are not sure if work needs to be shown for a particular problem, please ask.
  \item Your homework should be submitted electronically on GitHub.
  \item This problem set is due before 23:59 on Sunday December 3, 2023. No late assignments will be accepted.
\end{itemize}

\section*{Question 1: Economics}
\vspace{.25cm}
\noindent 	
In this question, use the \texttt{prestige} dataset in the \texttt{car} library. First, run the following commands:

\begin{verbatim}
install.packages(car)
library(car)
data(Prestige)
help(Prestige)
\end{verbatim} 


\noindent We would like to study whether individuals with higher levels of income have more prestigious jobs. Moreover, we would like to study whether professionals have more prestigious jobs than blue and white collar workers.

\newpage
\begin{enumerate}
	\item [(a)] Create a new variable \texttt{professional} by recoding the variable \texttt{type} so that professionals are coded as $1$, and blue and white collar workers are coded as $0$ (Hint: \texttt{ifelse}).
	\item [(b)] Run a linear model with \texttt{prestige} as an outcome and \texttt{income}, \texttt{professional}, and the interaction of the two as predictors (Note: this is a continuous $\times$ dummy interaction.)
	\item [(c)] Write the prediction equation based on the result.
	\item [(d)] Interpret the coefficient for \texttt{income}.
	\item [(e)] Interpret the coefficient for \texttt{professional}.
	\item [(f)] What is the effect of a \$1,000 increase in income on prestige score for professional occupations? In other words, we are interested in the marginal effect of income when the variable \texttt{professional} takes the value of $1$. Calculate the change in $\hat{y}$ associated with a \$1,000 increase in income based on your answer for (c).
	\item [(g)] What is the effect of changing one's occupations from non-professional to professional when her income is \$6,000? We are interested in the marginal effect of professional jobs when the variable \texttt{income} takes the value of $6,000$. Calculate the change in $\hat{y}$ based on your answer for (c).
\end{enumerate}

\textcolor{blue}{My Answer:}

```{R}
#install.packages("car")
## Question 1-a
library(car)
data(Prestige)

Prestige$professional <- ifelse(Prestige$type == 'prof', 1, 0)
table(Prestige$professional)

## Question 1-b
model <- lm(Prestige$prestige ~ (Prestige$income * Prestige$professional))
summary(model)
```

\textcolor{blue}{For the (c), based on the regression model from (b), we can find that the prediction equation can be denoted as:
  $$E[Y] = 21.142 + 0.003 \cdot \text{Income} + 37.781 \cdot \text{Processional} - 0.002 \cdot \text{Income} \cdot \text{Professional}$$
}
  
\textcolor{blue}{For the (d), based on the (c)'s equation, if the occupation is not professional, a \$1 increase in income leads to a 0.003 increase in prestige score.}

\textcolor{blue}{For the (e), based on the (c)'s equation, if someone who change one's occupations from non-professional to professional, it will leads to a 37.781 increases in its prestirage.}

\textcolor{blue}{For the (f), based on the (c)'s equation:
  $$E[Y] = 21.142 + 0.003 \times 1000 + 37.781 \times 1 - 0.002 \times 1000 \times 1 = 59.923$$
Thus, the difference is $59.923$.
}

\textcolor{blue}{For the (g), based on the (c)'s equation:
\begin{equation*}
  \begin{aligned}
    \text{Prof. = 6000, Income = 1}: E[Y] &= 21.142 + 0.003 \times 6000 + 37.781 \times 1 - 0.002 \times 6000 \times 1 = 64.923 \\
    \text{Prof. = 6000, Income = 0}: E[Y] &= 21.142 + 0.003 \times 6000 + 37.781 \times 0 - 0.002 \times 6000 \times 0 = 39.142 \\
  \end{aligned}
\end{equation*}
}

The difference when Income changes from $0$ to $1$ is $25.781$. 



\section*{Question 2: Political Science}
\vspace{.25cm}
\noindent 	Researchers are interested in learning the effect of all of those yard signs on voting preferences.\footnote{Donald P. Green, Jonathan	S. Krasno, Alexander Coppock, Benjamin D. Farrer,	Brandon Lenoir, Joshua N. Zingher. 2016. "The effects of lawn signs on vote outcomes: Results from four randomized field experiments." Electoral Studies 41: 143-150. } Working with a campaign in Fairfax County, Virginia, 131 precincts were randomly divided into a treatment and control group. In 30 precincts, signs were posted around the precinct that read, "For Sale: Terry McAuliffe. Don't Sellout Virgina on November 5." 

Below is the result of a regression with two variables and a constant.  The dependent variable is the proportion of the vote that went to McAuliff's opponent Ken Cuccinelli. The first variable indicates whether a precinct was randomly assigned to have the sign against McAuliffe posted. The second variable indicates
a precinct that was adjacent to a precinct in the treatment group (since people in those precincts might be exposed to the signs).

\vspace{.5cm}
\begin{table}[!htbp]
	\centering 
	\textbf{Impact of lawn signs on vote share}\\
	\begin{tabular}{@{\extracolsep{5pt}}lccc} 
		\\[-1.8ex] 
		\hline \\[-1.8ex]
		Precinct assigned lawn signs  (n=30)  & 0.042\\
		& (0.016) \\
		Precinct adjacent to lawn signs (n=76) & 0.042 \\
		&  (0.013) \\
		Constant  & 0.302\\
		& (0.011)
		\\
		\hline \\
	\end{tabular}\\
	\footnotesize{\textit{Notes:} $R^2$=0.094, N=131}
\end{table}

\begin{enumerate}
	\item [(a)] Use the results from a linear regression to determine whether having these yard signs in a precinct affects vote share (e.g., conduct a hypothesis test with $\alpha = .05$).
	\item [(b)]  Use the results to determine whether being next to precincts with these yard signs affects vote share (e.g., conduct a hypothesis test with $\alpha = .05$).
	\item [(c)] Interpret the coefficient for the constant term substantively.
	\item [(d)] Evaluate the model fit for this regression.  What does this	tell us about the importance of yard signs versus other factors that are not modeled?
\end{enumerate}  

\textcolor{blue}{Answer of Q2:}

```{R}
estimates <- c(0.042,0.042,0.302)
std_errors <- c(0.016, 0.013, 0.011)

t_score <- (estimates - 0) / (std_errors)
p_val <- 2 * pt(abs(t_score) , df = (131 - 3), lower.tail = F)

print(t_score)
print(p_val)
```
